### ISSUE TITLE
Error when build extension

### ISSUE THREAD

**Issue by afkadev** [quickshiftin/rolling-curl-ext#1]
[http://prntscr.com/m33q09](url)

**Comment by quickshiftin** [comment]
Hey Ezra, I haven't looked at this project in a long time. Initially it had some errors (meaning it never worked 100%). I was getting core dumps. It seemed like the code should be pretty close at the time, so I decided to put what I had here in case someone else was interested in getting it across the finish line.

**Comment by afkadev** [comment]
Can you help please fix the error, or make new fix version

**Comment by quickshiftin** [comment]
Have you looked at any of the pure PHP implementations, such as

* https://github.com/LionsAd/rolling-curl
* https://packagist.org/packages/chuyskywalker/rolling-curlz

That's your best bet to get going quickly.

**Comment by afkadev** [comment]
yes i know that, but i need build multithread bounced email check and i need hide my API URL, for security purposes

**Comment by afkadev** [comment]
hey can you help me ?

**Comment by quickshiftin** [comment]
See my prior comments. This extension is the same as the userspace code (multi-threaded), just that it should in theory be a little faster. As I mentioned it never was working, but it was close. I'll have to update the README to this effect. Currently, I have no plans to finish it, but if you or someone else wants to, it should be about 90%+ there.

**Comment by quickshiftin** [comment]
I updated the README w/ an explanation about the project.
